version: 1

rclone:
  remote: nxt
  base_path: Apps/pistomp-sync

options:
  auto_init_bisync: true
  create_keep_file: true

paths:
  pedalboards:
    enabled: true
    local: /home/pistomp/data/.pedalboards
    remote: pedalboards
    mode: bidirectional

  banks:
    enabled: true
    local: /home/pistomp/data/banks.json
    remote: banks.json
    mode: bidirectional

  favorites:
    enabled: true
    local: /home/pistomp/data/favorites.json
    remote: favorites.json
    mode: bidirectional

  user_files:
    enabled: false
    local: /home/pistomp/data/user-files
    remote: user-files
    mode: bidirectional

  pistomp_config:
    enabled: false
    local: /home/pistomp/data/config
    remote: config
    mode: bidirectional

  keys:
    enabled: false
    local: /home/pistomp/data/keys
    remote: keys
    mode: bidirectional
